/// 🍽️ MEAL PLAN DOMAIN MODELS
///
/// Data models representing meal plans and their components
/// These models define the structure of meal plan data from the backend
/// and are used throughout the meal plan feature for state management
///
/// Models:
/// - MealPlanModel: Core meal plan metadata
/// - MealPlanItemModel: Individual meal within a plan
/// - MealPlanSummary: Aggregated plan statistics
/// - MealPlanGenerationResult: Complete generated meal plan with items and summary

/// 📋 CORE MEAL PLAN MODEL
///
/// Represents a meal plan at the highest level
/// Contains metadata about the plan but not individual meals
///
/// Fields:
/// - id: Unique identifier (MongoDB ObjectId)
/// - days: Number of days in the plan (3, 7, 14, 30, etc.)
/// - targetCalories: Daily calorie target (if specified)
/// - actualCalories: Average actual calories per day in the plan
/// - status: Current status ('draft', 'saved', 'archived', etc.)
/// - aiGenerated: Whether plan was generated by AI (true) or manually created (false)
/// - date: When the plan was created/last modified
///
/// Usage:
/// ```dart
/// final mealPlan = MealPlanModel(
///   id: '123abc',
///   days: 7,
///   targetCalories: 2000,
///   aiGenerated: true,
/// );
/// ```
class MealPlanModel {
  final String id;
  final int days;
  final double? targetCalories;
  final double? actualCalories;
  final String? status;
  final bool aiGenerated;
  final DateTime? date;

  MealPlanModel({
    required this.id,
    required this.days,
    required this.aiGenerated,
    this.targetCalories,
    this.actualCalories,
    this.status,
    this.date,
  });

  /// Factory constructor to deserialize from API JSON response
  ///
  /// Maps backend response to MealPlanModel:
  /// - '_id' → id (MongoDB uses _id)
  /// - Handles missing fields with defaults
  /// - Parses date string to DateTime
  ///
  /// Example API response:
  /// ```json
  /// {
  ///   "_id": "507f1f77bcf86cd799439011",
  ///   "days": 7,
  ///   "targetCalories": 2000,
  ///   "actualCalories": 1950,
  ///   "status": "saved",
  ///   "aiGenerated": true,
  ///   "date": "2024-03-15T10:30:00Z"
  /// }
  /// ```
  factory MealPlanModel.fromJson(Map<String, dynamic> json) {
    return MealPlanModel(
      id: json['_id']?.toString() ?? '',
      days: (json['days'] as num?)?.toInt() ?? 1,
      targetCalories: (json['targetCalories'] as num?)?.toDouble(),
      actualCalories: (json['actualCalories'] as num?)?.toDouble(),
      status: json['status']?.toString(),
      aiGenerated: json['aiGenerated'] == true,
      date: json['date'] != null
          ? DateTime.tryParse(json['date'].toString())
          : null,
    );
  }
}

/// 🍲 MEAL PLAN ITEM MODEL
///
/// Represents a single meal within a meal plan
/// Contains nutritional info, recipe reference, and tracking data
///
/// Fields:
/// - id: Unique identifier for this meal plan item
/// - recipeId: Reference to the recipe used for this meal
/// - mealType: Type of meal ('breakfast', 'lunch', 'dinner', 'snack')
/// - servings: Number of servings for this meal (used for scaling)
/// - calories/protein/carbohydrates/fat: Macronutrient values
/// - dayIndex: Which day in the meal plan (0-indexed, day 0 = first day)
/// - recipeName: Display name of recipe (for UI without needing to lookup)
/// - recipeImageUrl: Image URL for recipe (for preview)
///
/// Optimization Fields:
/// - userRating: 1-5 star rating (optional, null if not rated)
/// - userAction: User interaction ('liked', 'disliked', 'none')
/// - isLocked: Whether this meal is locked for optimization (user wants to keep it)
///
/// Tracking Fields:
/// - isEaten: Whether user marked this meal as completed/eaten
/// - eatenDate: When the meal was marked as eaten
///
/// Usage:
/// ```dart
/// final mealItem = MealPlanItemModel(
///   id: '456def',
///   recipeId: '789ghi',
///   mealType: 'breakfast',
///   servings: 2,
///   calories: 450,
///   dayIndex: 0,
/// );
/// ```
class MealPlanItemModel {
  final String id;
  final String? recipeId;
  final String mealType;
  final int servings;
  final double calories;
  final double protein;
  final double carbohydrates;
  final double fat;
  final int dayIndex;
  final String? recipeName;
  final String? recipeImageUrl;
  // NEW FIELDS FOR OPTIMIZATION
  final int? userRating;
  final String userAction;
  final bool isLocked;
  // NEW FIELDS FOR MEAL TRACKING
  final bool isEaten;
  final DateTime? eatenDate;

  MealPlanItemModel({
    required this.id,
    this.recipeId,
    required this.mealType,
    required this.servings,
    required this.calories,
    required this.protein,
    required this.carbohydrates,
    required this.fat,
    required this.dayIndex,
    this.recipeName,
    this.recipeImageUrl,
    this.userRating,
    this.userAction = 'none',
    this.isLocked = false,
    this.isEaten = false,
    this.eatenDate,
  });

  /// Factory constructor to deserialize from API JSON response
  ///
  /// Handles nested recipe object from API:
  /// - Recipe data may be a full object (via populate) or just an ID string
  /// - Extracts recipe._id for recipeId reference
  /// - Extracts recipe.name and recipe.imageUrl for display
  ///
  /// Example API response:
  /// ```json
  /// {
  ///   "_id": "item_001",
  ///   "recipeId": {
  ///     "_id": "recipe_123",
  ///     "name": "Pancakes",
  ///     "imageUrl": "https://...",
  ///   },
  ///   "mealType": "breakfast",
  ///   "servings": 2,
  ///   "calories": 450,
  ///   "protein": 15,
  ///   "carbohydrates": 60,
  ///   "fat": 18,
  ///   "dayIndex": 0,
  ///   "userRating": 4,
  ///   "userAction": "liked",
  ///   "isLocked": false,
  ///   "isEaten": false
  /// }
  /// ```
  factory MealPlanItemModel.fromJson(Map<String, dynamic> json) {
    final recipe = json['recipeId'] is Map<String, dynamic>
        ? json['recipeId'] as Map<String, dynamic>
        : null;

    return MealPlanItemModel(
      id: json['_id']?.toString() ?? '',
      recipeId: recipe?['_id']?.toString() ?? json['recipeId']?.toString(),
      mealType: json['mealType']?.toString() ?? 'snack',
      servings: (json['servings'] as num?)?.toInt() ?? 1,
      calories: (json['calories'] as num?)?.toDouble() ?? 0,
      protein: (json['protein'] as num?)?.toDouble() ?? 0,
      carbohydrates: (json['carbohydrates'] as num?)?.toDouble() ?? 0,
      fat: (json['fat'] as num?)?.toDouble() ?? 0,
      dayIndex: (json['dayIndex'] as num?)?.toInt() ?? 0,
      recipeName: recipe?['name']?.toString(),
      recipeImageUrl: recipe?['imageUrl']?.toString(),
      userRating: (json['userRating'] as num?)?.toInt(),
      userAction: json['userAction']?.toString() ?? 'none',
      isLocked: json['isLocked'] == true,
      isEaten: json['isEaten'] == true,
      eatenDate: json['eatenDate'] != null
          ? DateTime.tryParse(json['eatenDate'].toString())
          : null,
    );
  }

  /// Create a modified copy with specified fields changed
  ///
  /// Follows immutable pattern for state management
  /// Returns new instance with replaced fields
  /// Unchangedfields use current values
  ///
  /// Usage:
  /// ```dart
  /// // Mark meal as eaten
  /// final eaten = original.copyWith(
  ///   isEaten: true,
  ///   eatenDate: DateTime.now(),
  /// );
  ///
  /// // Rate a meal
  /// final rated = original.copyWith(userRating: 5);
  /// ```
  MealPlanItemModel copyWith({
    String? id,
    String? recipeId,
    String? mealType,
    int? servings,
    double? calories,
    double? protein,
    double? carbohydrates,
    double? fat,
    int? dayIndex,
    String? recipeName,
    String? recipeImageUrl,
    int? userRating,
    String? userAction,
    bool? isLocked,
    bool? isEaten,
    DateTime? eatenDate,
  }) {
    return MealPlanItemModel(
      id: id ?? this.id,
      recipeId: recipeId ?? this.recipeId,
      mealType: mealType ?? this.mealType,
      servings: servings ?? this.servings,
      calories: calories ?? this.calories,
      protein: protein ?? this.protein,
      carbohydrates: carbohydrates ?? this.carbohydrates,
      fat: fat ?? this.fat,
      dayIndex: dayIndex ?? this.dayIndex,
      recipeName: recipeName ?? this.recipeName,
      recipeImageUrl: recipeImageUrl ?? this.recipeImageUrl,
      userRating: userRating ?? this.userRating,
      userAction: userAction ?? this.userAction,
      isLocked: isLocked ?? this.isLocked,
      isEaten: isEaten ?? this.isEaten,
      eatenDate: eatenDate ?? this.eatenDate,
    );
  }
}

/// 📊 MEAL PLAN SUMMARY MODEL
///
/// Aggregated statistics for a meal plan
/// Provides high-level overview without needing to iterate items
/// Used for dashboard display and quick statistics
///
/// Fields:
/// - totalMeals: Count of all meals in plan
/// - days: Number of days (should match MealPlanModel.days)
/// - avgCaloriesPerDay: Average calories per day (useful for targets)
///
/// Usage:
/// ```dart
/// final summary = MealPlanSummary(
///   totalMeals: 21,
///   days: 7,
///   avgCaloriesPerDay: 2000,
/// );
/// print('${summary.totalMeals} meals over ${summary.days} days');
/// ```
class MealPlanSummary {
  final int totalMeals;
  final int days;
  final double avgCaloriesPerDay;

  MealPlanSummary({
    required this.totalMeals,
    required this.days,
    required this.avgCaloriesPerDay,
  });

  /// Factory constructor to deserialize from API JSON response
  ///
  /// Example API response:
  /// ```json
  /// {
  ///   "totalMeals": 21,
  ///   "days": 7,
  ///   "avgCaloriesPerDay": 2000
  /// }
  /// ```
  factory MealPlanSummary.fromJson(Map<String, dynamic> json) {
    return MealPlanSummary(
      totalMeals: (json['totalMeals'] as num?)?.toInt() ?? 0,
      days: (json['days'] as num?)?.toInt() ?? 1,
      avgCaloriesPerDay: (json['avgCaloriesPerDay'] as num?)?.toDouble() ?? 0,
    );
  }
}

/// 🎯 MEAL PLAN GENERATION RESULT MODEL
///
/// Complete result of meal plan generation
/// Contains all data needed to display and manage a generated plan
/// Returned by backend after generation or fetching
///
/// Fields:
/// - mealPlan: The core meal plan metadata
/// - items: List of all meals in the plan (grouped by day)
/// - summary: Aggregated plan statistics
///
/// Architecture:
/// ```
/// MealPlanGenerationResult
/// ├─ MealPlanModel (1)
/// │  └─ Core plan info
/// ├─ List<MealPlanItemModel> (21 items for 7-day plan)
/// │  ├─ Day 0: breakfast, lunch, dinner, snack
/// │  ├─ Day 1: breakfast, lunch, dinner, snack
/// │  └─ ... (continues)
/// └─ MealPlanSummary (1)
///    └─ Aggregate stats
/// ```
///
/// Usage:
/// ```dart
/// final result = MealPlanGenerationResult(
///   mealPlan: MealPlanModel(...),
///   items: [
///     MealPlanItemModel(mealType: 'breakfast', dayIndex: 0, ...),
///     MealPlanItemModel(mealType: 'lunch', dayIndex: 0, ...),
///     // ... more items
///   ],
///   summary: MealPlanSummary(...),
/// );
///
/// // Get all meals for day 0
/// final day0Meals = result.items.where((m) => m.dayIndex == 0).toList();
///
/// // Calculate total calories in plan
/// final totalCals = result.items.fold<double>(
///   0,
///   (sum, item) => sum + item.calories,
/// );
/// ```
class MealPlanGenerationResult {
  final MealPlanModel mealPlan;
  final List<MealPlanItemModel> items;
  final MealPlanSummary? summary;

  MealPlanGenerationResult({
    required this.mealPlan,
    required this.items,
    this.summary,
  });

  /// Factory constructor to deserialize from API JSON response
  ///
  /// Handles variable API response structures:
  /// - mealPlan: Required, contains plan metadata
  /// - items: Array of meal items, safely filters non-map elements
  /// - summary: Optional summary object (may be null)
  ///
  /// Example API response:
  /// ```json
  /// {
  ///   "mealPlan": {
  ///     "_id": "plan_001",
  ///     "days": 7,
  ///     "aiGenerated": true
  ///   },
  ///   "items": [
  ///     {
  ///       "_id": "item_1",
  ///       "mealType": "breakfast",
  ///       "recipeId": "recipe_123",
  ///       ...
  ///     },
  ///     // ... 20 more items for 7-day plan
  ///   ],
  ///   "summary": {
  ///     "totalMeals": 21,
  ///     "days": 7,
  ///     "avgCaloriesPerDay": 2000
  ///   }
  /// }
  /// ```
  factory MealPlanGenerationResult.fromJson(Map<String, dynamic> json) {
    final itemsJson = (json['items'] as List<dynamic>? ?? [])
        .whereType<Map<String, dynamic>>()
        .toList();

    return MealPlanGenerationResult(
      mealPlan: MealPlanModel.fromJson(
        (json['mealPlan'] as Map<String, dynamic>?) ?? {},
      ),
      items: itemsJson.map(MealPlanItemModel.fromJson).toList(),
      summary: json['summary'] is Map<String, dynamic>
          ? MealPlanSummary.fromJson(json['summary'] as Map<String, dynamic>)
          : null,
    );
  }
}
